Algoritmo "ficha1_ex1.7"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2026
Var
// Secção de Declarações das variáveis
antecessor:inteiro
numero:inteiro

Inicio
// Secção de Comandos, procedimento, funções, operadores, etc...
escreval("programa que escrevo o nome antecessor")
escreval("Digite um numero: ")
leia(numero)
escreval("Sem numero antecessor")
antecessor <- numero

escreval("Digite um numero: ")
leia(numero)
escreval("O numero antecessor é:",antecessor)

Fimalgoritmo