Algoritmo "ficha1_ex1.3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2026
Var
// Secção de Declarações das variáveis
celsius:inteiro
fahrenheit:inteiro

Inicio
// Secção de Comandos, procedimento, funções, operadores, etc...
escreval("*****Bemvindo(a) ao conversor de celsius para fahrenheit*****")
escreval("Digite o valor de celsius: ")
leia(celsius)

fahrenheit <- 32+(18*celsius)
escreval("O valor em fahrenheit é: ",fahrenheit)

Fimalgoritmo