# Configurações globais do Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true

# Estilo de código Kotlin
kotlin.code.style=official

# AndroidX e Jetifier (Jetifier desativado pois o projeto é moderno)
android.useAndroidX=true
android.enableJetifier=false

# Melhorias de performance e isolamento de recursos
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Desativar suporte nativo a Kotlin do AGP 9.0 para evitar conflito com o plugin externo
android.builtInKotlin=true
android.newDsl=true
